// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Project struct {
	ID          string  `json:"id"`
	Slug        string  `json:"slug"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Image       string  `json:"image"`
	URL         *string `json:"url"`
	Git         *string `json:"git"`
	Tags        []*Tag  `json:"tags"`
}

type Tag struct {
	ID    string `json:"id"`
	Slug  string `json:"slug"`
	Title string `json:"title"`
}

type TagInterface struct {
	Tag   *Tag `json:"tag"`
	Total int  `json:"total"`
}
