version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/go.dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/app:cached
    command:
      air

  web:
    build:
      context: .
      dockerfile: ./docker/web.dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/app:cached
      - node_modules:/app/node_modules:delegated
      - yarn_config:/usr/local/share/.config 

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - backend

volumes:
  node_modules:
  yarn_config: