version: "3.8"

services:
  graphql:
    build:
      context: ./graphql
      dockerfile: ../docker/go.dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./graphql:/usr/app:cached
    command:
      air
    environment:
      MONGODB_URI: ''

  web:
    build:
      context: .
      dockerfile: ./docker/web.dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/app:cached
      - node_modules:/app/node_modules:delegated  

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    logging:
      driver: none

volumes:
  node_modules:
