version: "3.8"

services:
  elixir:
    build:
      context: ./backend
      dockerfile: ../docker/dev/elixir.Dockerfile
      # dockerfile: ../docker/prod/elixir.Dockerfile
    command: mix phx.server
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
    environment: &app_environment
      MYSQL_HOSTNAME: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: db
      ENV: development
    volumes:
      - ./backend:/usr/app:cached
    depends_on:
      - mysql

  node:
    build:
      context: ./frontend
      dockerfile: ../docker/dev/node.Dockerfile
    ports:
      - 3000:3000
    environment:
      NEXT_TELEMETRY_DISABLED: 1
      NGINX_HOST: 'nginx'
    volumes:
      - ./frontend:/usr/app:cached
      - node_modules:/app/node_modules:delegated
      - yarn_config:/usr/local/share/.config 

  mysql:
    mem_limit: 1g
    image: mysql:8.0.20
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    environment: *app_environment
    healthcheck:
      test: mysqladmin ping -h localhost -u mysql -pmysql
      timeout: 20s
      retries: 10

  nginx:
    image: nginx:latest
    volumes:
      - ./config/dev/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - elixir
      - node
      
volumes:
  node_modules:
  yarn_config: