version: "3.8"

services:
  go:
    build:
      context: ./backend
      dockerfile: ../docker/dev/go.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/app:cached
    command:
      air

  node:
    build:
      context: ./frontend
      dockerfile: ../docker/dev/web.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/app:cached
      - node_modules:/app/node_modules:delegated
      - yarn_config:/usr/local/share/.config 

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - go
      - node
  
  # Test nginx prod
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./docker/prod/nginx.Dockerfile
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - go
  #     - node
  

volumes:
  node_modules:
  yarn_config: