root = "." 
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main server.go"
bin = "tmp/main"
full_bin = "./tmp/main"
log = "air_errors.log"
include_ext = ["go", "resolvers.go"]
include_dir = []
exclude_dir = ["tmp"]
exclude_file = []
delay = 1000 # ms
stop_on_error = false

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true