name: Production

on:
  push:
    branches: [main]

jobs:
  react:
    name: React Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Yarn Install
        run: yarn
      - name: Yarn Build
        run: yarn build
      - name: Yarn Test
        run: yarn test
      - name: Yarn Lint
        run: yarn lint

  env:
    name: Setup Env
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Make Environment File
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
          envkey_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          envkey_BUCKET               : ${{ secrets.BUCKET }}
          file_name                   : .env 
      - name: Upload ENV
        uses: actions/upload-artifact@v2
        with:
          name: env
          path: .env
  
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    needs: [env]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Download ENV
        uses: actions/download-artifact@v2
        with:
          name: env
      - name: Source ENV
        run : source .env
      - name: Terraform Check & Init
        run : |
          terraform -chdir=terraform fmt -check 
          terraform -chdir=terraform init
      - name: Terraform Apply
        run : terraform -chdir=terraform apply -auto-approve

  s3:
    name: Sync with S3
    runs-on: ubuntu-latest
    needs: [react, terraform]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Yarn Install
        run: yarn
      - name: Yarn Build
        run: yarn build
      - name: Sync
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET         : "dylank.io"
          AWS_ACCESS_KEY_ID     : ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION            : "ap-southeast-2"
