name: Production

on:
  push:
    branches: [main]

jobs:
  react:
    name: React Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Yarn Install
        run: cd frontend && yarn
      - name: Yarn Test
        run: cd frontend && yarn test
      - name: Yarn Lint
        run: cd frontend && yarn lint
      - name: Yarn Build
        run: cd frontend && yarn build
        
  ecr-elixir:
    name: Upload elixir image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region            : "ap-southeast-2"
      - name: Upload
        run: sh deploy.sh ecr-core-dylank-elixir ${{ secrets.AWS_URL }} ap-southeast-2 docker/prod/elixir.Dockerfile ./backend
  
  ecr-node:
    name: Upload node image to ECR
    runs-on: ubuntu-latest
    needs: [react]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region            : "ap-southeast-2"
      - name: Upload
        run: sh deploy.sh ecr-core-dylank-node ${{ secrets.AWS_URL }} ap-southeast-2 docker/prod/node.Dockerfile .

  ecr-nginx:
    name: Update nginx image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region            : "ap-southeast-2"
      - name: Upload
        run: sh deploy.sh ecr-core-dylank-nginx ${{ secrets.AWS_URL }} ap-southeast-2 docker/prod/nginx.Dockerfile .

  ecs:
    name: Deploy new service
    runs-on: ubuntu-latest
    needs: [ecr-elixir, ecr-node, ecr-nginx]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region            : "ap-southeast-2"
      - name: Update service
        run: aws ecs update-service --cluster main-cluster --service ecs-service-core-dylank --force-new-deployment --region ap-southeast-2 >> dev.txt
