name: Test

on:
  pull_request:
    branches: [main]

jobs:
  react:
    name: React Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Yarn Install
        run: yarn
      - name: Yarn Build
        run: yarn build
      - name: Yarn Test
        run: yarn test
      - name: Yarn Lint
        run: yarn lint