name: Test

on:
  pull_request:
    branches: [main]

jobs:
  react:
    name: React Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Yarn Install
        run: yarn
      - name: Yarn Build
        run: yarn build
      - name: Yarn Test
        run: yarn test
      - name: Yarn Lint
        run: yarn lint
    
  go:
    name: Go Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: graphql
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - name: Go Test
        run: go test -v ./...
      - name: Go Modules Download
        run: go mod download
      - name: Go Build
        run: go build -o server server.go

  golangci:
    name: Go Lint
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: graphql
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: ./...